In [1]:
import numpy as np

In [2]:
dizi = np.array([1, 2, 3, 4, 5])
print(dizi)
print(type(dizi))

#Python listelerini veya diğer dizileri NumPy dizisine  dönüştürmek için 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
dizi = np.arange(0, 10, 2) 
print(dizi)

 # 0'dan 10'a kadar 2'şer artan dizi

[0 2 4 6 8]


In [4]:
dizi = np.linspace(0, 10, 5)  
print(dizi)

# 0 ile 10 arasında 5 eşit aralıklı sayı

[ 0.   2.5  5.   7.5 10. ]


In [6]:
sıfır_dizi = np.zeros((3, 3))  
bir_dizi = np.ones((2, 4))    

print(sıfır_dizi)
print(bir_dizi)

#Belirtilen boyutta sıfır veya bir içeren yukarıda 0 için 3x3 sıfır matris ve 1 için 2x4 matris

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
dizi1 = np.random.rand(3, 3)  
dizi2 = np.random.randn(2, 2) 

print(dizi1)
print(dizi2)

[[0.91395295 0.5500755  0.26414354]
 [0.26345558 0.76840308 0.04550707]
 [0.79564994 0.35485458 0.10446362]]
[[ 0.03721036  0.82088053]
 [-0.87511318 -0.58244183]]


In [9]:
dizi = np.arange(12)  
yeni_dizi = dizi.reshape(3, 4)  

print(yeni_dizi)

#Bir dizinin şeklini değiştirmek için

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

birlestir = np.concatenate((dizi1, dizi2))
print(birlestir)

#İki veya daha fazla diziyi birleştirmek için

[1 2 3 4 5 6]


In [12]:
dizi = np.array([1, 2, 3, 4, 5])

print(np.sum(dizi))  
print(np.mean(dizi)) 
print(np.min(dizi)) 
print(np.max(dizi)) 

# fonksiyonlar dizinin toplamını, ortalamasını, minimum ve maksimum değerini hesaplamak için

15
3.0
1
5


In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

carpim = np.dot(A, B)
print(carpim)

#İki dizinin matris çarpımını hesaplamak için

[[19 22]
 [43 50]]


In [15]:
dizi = np.array([10, 20, 30, 40, 50])
sonuc = np.where(dizi > 25)

print(sonuc) 

#Belirli bir koşulu sağlayan elemanların konumunu veya değerini almak için

(array([2, 3, 4]),)
